# Kapps listed under this key will be installed if they are not currently
# installed in the target cluster.
present:

  # The simplest manifest entry uses defaults for e.g. the helm namespace,
  # chart name, etc. when using `helm` as the installer.
  cert-manager:       # Globally-unique identifier. For helm this corresponds
                      # to the release name. If that's too restrictive we could
                      # generate a globally-unique identifier based on the
                      # manifest, but for now we'll keep it simple.

    installer: helm             # The plugin that know how to install this kapp

    # Sources to checkout as siblings in the cache for this kapp. This allows
    # creating a cache entry from e.g. the actual kapp source, a directory of
    # shared makefiles, and/or pulling in `values.yaml` files etc. from a
    # separately versioned source.
    sources:
    - url: git@github.com:helm/charts.git
      branch: master
      path: charts/stable/cert-manager/
    - url: git@github.com:sugarkube/sugarkube.git
      branch: master
      path: examples/values/cert-manager/values/
    - url: git@github.com:sugarkube/sugarkube.git
      branch: master
      path: examples/common-makefiles/

  # This entry demonstrates how to explicitly declare values.
  #
  # Unique identifier. The same kapp can be installed multiple times provided
  # this is unique per instance.
  wordpress-site1:
    installer: helm               # The plugin that know how to install this kapp
    name: wordpress               # Defaults to the identifier
    meta:                         # installer-specific values
      namespace: wordpress-sites  # Helm-specific value

    # Sources to checkout as siblings in the cache for this kapp. This allows
    # creating a cache entry from e.g. the actual kapp source, a directory of
    # shared makefiles, and/or pulling in `values.yaml` files etc. from a
    # separately versioned source.
    sources:
    - url: git@github.com:helm/charts.git
      # if this was our repo a good pattern could be to create a signed tag for
      # each release called `<chart>-<version>`.
      branch: master
      path: charts/stable/wordpress/
    - url: git@github.com:sugarkube/sugarkube.git
      branch: master
      # this lets us reuse the same kapp parameterised differently per instance
      path: examples/values/wordpress/site1/values/
      # Name of the dest dir to write to in the cache. Defaults to the last
      # component of the path which in this case is the same as what we're
      # demonstrating below. But here's how to override it explicitly anyway.
      dest: values
    - url: git@github.com:sugarkube/sugarkube.git
      branch: master
      path: examples/common-makefiles/
