# Default values for all clusters that use this profile
is_prod_cluster: false

hosted_zone: example.com            # The domain to host your stuff under.

kops:
  kubernetes_version: 1.9.6
  # state_store:                    # A default is generated but it's overrideable too
  ssh_key: "/path/to/ssh.pub"       # Path to the SSH key used to create the kops cluster when using kops
  api_loadbalancer_type: public     # More kops settings...
  dns: public
  authorization: RBAC
  networking: calico
  topology: private

  spec:                             # The kops config will be downloaded and this
    docker:                         # will be patched into the spec before
      logLevel: warn                # applying it to update the cluster config.
      logOpt:                       # This allows kops clusters to be fully
      - max-size: 10m               # customised and updated automatically.
      - max-file: 5
